#!/bin/bash

# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

set -u

make_key() {
    local name=$1
    local length=${2:-2048}
    echo "Generating $name ($length-bit)..."
    openssl genrsa -out "${name}.pem" $length 2>/dev/null
    openssl req -new -x509 -key "${name}.pem" -out "${name}.x509.pem" -days 10000 -subj '/C=US/ST=California/L=Mountain View/O=Android/OU=Android/CN=Android/emailAddress=android@android.com' 2>/dev/null
    openssl pkcs8 -in "${name}.pem" -topk8 -outform DER -out "${name}.pk8" -nocrypt 2>/dev/null
    rm -f "${name}.pem"
}

# Generate Android.bp
echo "// DO NOT EDIT THIS FILE MANUALLY" > Android.bp

for key in $(grep -o :\.\*override keys.mk | sort -u); do
    echo "" >> Android.bp
    echo "android_app_certificate {" >> Android.bp
    echo "    name: \"${key:1}\"," >> Android.bp
    echo "    certificate: \"${key:1}\"," >> Android.bp
    echo "}" >> Android.bp
done

# Standard AOSP Keys
make_key avb 4096
make_key bluetooth 2048
make_key cts_uicc_2021 2048
make_key cyngn-app 2048
make_key media 2048
make_key networkstack 2048
make_key nfc 2048
make_key platform 2048
make_key releasekey 2048
make_key sdk_sandbox 2048
make_key shared 2048
make_key testcert 2048
make_key testkey 2048
make_key verity 2048

# Certificate Overrides
for key in $(grep -o :\.\*override keys.mk | sort -u); do
    make_key ${key:1} 4096
done
